### ISSUE TITLE
Do we need to release a new version?

### ISSUE THREAD

**Issue by lpil** [gleam-lang/tree-sitter-gleam#100]
Hello!

I see there has been no new "version" in some time. Is this why GitHub is using an outdated version of the code which doesn't support Gleam syntax?

Cheers,
Louis

**Comment by the-mikedavis** [comment]
I'm not sure if github uses tags or commit hashes (\cc @patrickt)

I haven't looked at cutting a release in a while, I think there's some catch-up to do anyways to match the Gleam versions since the last release

**Comment by lpil** [comment]
Is the expectation that people ignore the existing releases and always use the main branch? If so, could we remove the existing releases to avoid confusion?

**Comment by the-mikedavis** [comment]
I'm pretty sure that all editors use commit hashes - I'm sure that Helix and NeoVim do at least. For tree-sitter-elixir we only use releases when publishing the Rust bindings to crates.io and the versions aren't synced to Elixir version numbers.

I'd be in favor of removing the releases. What do you think @J3RN?

**Comment by J3RN** [comment]
Hi, sorry for the delay.

I believe my original rationale for versioning was that since Gleam's syntax was changing frequently, having corresponding tree-sitter-gleam versions would allow someone to work with a codebase that was a smidge behind the current Gleam version.  I believe this is largely no longer a concern, and therefore we can do away with versioning and the old tags/releases.

**Comment by lpil** [comment]
Thank you!
