### ISSUE TITLE
Add reserved keywords

### ISSUE THREAD

**Issue by lpil** [gleam-lang/tree-sitter-gleam#80]
Hello!

Gleam has some reserved keywords. Would it make sense to add these to the grammar? So they get highlighted appropriately if used.

https://github.com/gleam-lang/gleam/blob/0008b79d2eedfa2dd4d13efd67fa063e7ada285d/compiler-core/src/parse.rs#L2792-L2793

Thanks,
Louis

**Comment by the-mikedavis** [comment]
I changed the reference highlights a little so that these highlight as warnings: https://github.com/gleam-lang/tree-sitter-gleam/commit/78123c13e3328b52f989610d8c49f762ce8559db

I think we want to hold off on adding them to the parser for now - I think we want to wait until we know how they might be used in the future so we can parse them correctly

**Comment by lpil** [comment]
Nice, thank you
